# Generated by Django 4.2.26 on 2025-11-28 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 11, 28, 14, 18, 49, 358322), verbose_name='Опубликована'),
        ),
    ]
